### ISSUE TITLE
I don't know much about C++, how do I compile it to get the spi file?

### ISSUE THREAD

**Issue by zhang-weiyu** [toroidj/iftwic#1]
I don't know much about C++, how do I compile to get the spi file? I tried to use `mingw32-make` under windows and it shows `makefile:5: *** missing separator.  Stop.`

**Comment by toroidj** [comment]
The makefile is not for GNU make(mingw32-make). 
You need to create a new makefile for Mingw32.
Also, I have not confirmed that I can compile source with Mingw32.

**Comment by zhang-weiyu** [comment]
> The makefile is not for GNU make(mingw32-make). You need to create a new makefile for Mingw32. Also, I have not confirmed that I can compile source with Mingw32.

I just tried to open the project with vs2022 and compile it, and it seems to be successful :)
